import { CourseInfo } from './types';

export const coursesInfo: CourseInfo[] = [
  {
    course: ['Applied Mathematics I', 'Math1101'],
    year: ['First'],
    semester: ['sem1'],
    department: [
      [
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoANS', 'SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: ['Introduction to Computing', 'CSE1101'],
    year: ['First'],
    semester: ['sem1'],
    department: [
      [
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoANS', 'SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: ['General Physics-I', 'Phys1101'],
    year: ['First'],
    semester: ['sem1'],
    department: [
      [
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoANS', 'SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: ['Health & Physical Education I', 'HPEd1011'],
    year: ['First'],
    semester: ['sem1'],
    department: [
      [
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoANS', 'SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: [
      'Logic and Critical Thinking',
      'LAR1012',
      'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
    ],
    year: ['First'],
    semester: ['sem1', 'sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
      [
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [
      ['SoCEA', 'SoEEC', 'SoMCME'],
      ['SoANS', 'SoCEA', 'SoEEC', 'SoMCME'],
    ],
  },
  {
    course: [
      'Civic and Ethical Education',
      'LAR1011',
      'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
    ],
    year: ['First'],
    semester: ['sem1', 'sem2'],
    department: [
      [
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [
      ['SoANS', 'SoCEA', 'SoEEC', 'SoMCME'],
      ['SoCEA', 'SoEEC', 'SoMCME'],
    ],
  },
  {
    course: ['Communicative English Skills', 'ENG1011'],
    year: ['First'],
    semester: ['sem1', 'sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
      ['AB', 'AC', 'P', 'IC', 'AG', 'AM', 'AP'],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME'], ['SoANS']],
  },
  {
    course: [
      'Applied Mathematics II',
      'Math1102',
      'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
    ],
    year: ['First'],
    semester: ['sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
      ],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME', 'SoANS']],
  },
  {
    course: [
      'Introduction to Emerging Technologies',
      'CSEg1102',
      'BQACAgQAAxkBAAIHF2HpWjC7fGFjs-9tw0DnwJ45FEK9AAKaCwACCoZIUFfuoRrXPXH3IwQ',
    ],
    year: ['First'],
    semester: ['sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
      ],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME', 'SoANS']],
  },
  {
    course: ['Health & Physical Education II', 'HPEd1012'],
    year: ['First'],
    semester: ['sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
        'AB',
        'AC',
        'P',
        'IC',
        'AG',
        'AM',
        'AP',
      ],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME', 'SoANS']],
  },
  {
    course: ['Fundamentals of Programming', 'CSEg1104'],
    year: ['First'],
    semester: ['sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: ['Engineering Drawing', 'DME1102'],
    year: ['First'],
    semester: ['sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: ['Basic Writing Skills', 'ENG1102'],
    year: ['First'],
    semester: ['sem2'],
    department: [
      [
        'ARCH',
        'CivE',
        'GE',
        'WRE',
        'CSE',
        'SE',
        'ECE',
        'EPCE',
        'ChE',
        'MSE',
        'ME',
      ],
    ],
    school: [['SoCEA', 'SoEEC', 'SoMCME']],
  },
  {
    course: ['Data Structure and Algorithm', 'CSE2101'],
    year: ['Second'],
    semester: ['sem1'],
    department: [['CSE', 'SE', 'ECE', 'EPCE']],
    school: [['SoEEC']],
  },
  {
    course: ['Electronic Circuit', 'ECE2101'],
    year: ['Second'],
    semester: ['sem1'],
    department: [['CSE', 'SE', 'ECE', 'EPCE']],
    school: [['SoEEC']],
  },
  {
    course: ['Fundamental of Electrical Engineering', 'PCE2101'],
    year: ['Second'],
    semester: ['sem1'],
    department: [['CSE', 'SE', 'ECE', 'EPCE']],
    school: [['SoEEC']],
  },
  {
    course: [
      'Applied Mathematics III',
      'MATH2051',
      'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
    ],
    year: ['Second'],
    semester: ['sem1'],
    department: [['CSE', 'SE', 'ECE', 'EPCE']],
    school: [['SoEEC']],
  },
  {
    course: ['Principle of Economics', 'SOS311'],
    year: ['Second'],
    semester: ['sem1'],
    department: [['CSE', 'SE', 'ECE', 'EPCE']],
    school: [['SoEEC']],
  },
];

export let course = {
  SoEEC: {
    First: {
      sem1: [
        ['Applied Mathematics I', 'Math1101'],
        ['General Physics-I', 'Phys1101'],
        ['General Chemistry', 'Chem1101'],
        ['Introduction to Computing', 'CSE1101'],
        ['Communicative English Skills', 'ENG1011'],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
        ['Health & Physical Education I', 'HPEd1011'],
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
      ],
      sem2: [
        [
          'Applied Mathematics II',
          'Math1102',
          'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
        ],
        [
          'Introduction to Emerging Technologies',
          'CSEg1102',
          'BQACAgQAAxkBAAIHF2HpWjC7fGFjs-9tw0DnwJ45FEK9AAKaCwACCoZIUFfuoRrXPXH3IwQ',
        ],
        ['Fundamentals of Programming', 'CSEg1104'],
        ['Engineering Drawing', 'DME1102'],
        ['Basic Writing Skills', 'ENG1102'],
        ['Health & Physical Education II', 'HPEd1012'],
        ['Logic and Critical Thinking', 'LAR1012'],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
      ],
    },
    CSE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [
          ['Object Oriented Programming', 'CSE2202'],
          ['Discrete Mathematics for CSE', 'CSE2206'],
          ['Digital Logic Design', 'ECE3204'],
          ['Database Systems', 'CSE3207'],
          ['Electronic circuit II', 'ECE2202'],
          ['System Programming', 'CSE2320'],
          ['Computer Graphics', 'CSE3310'],
        ],
      },
      Third: {
        sem1: [
          ['Algorithms', 'CSE3211'],
          ['Probability and Random Process', 'ECE3103'],
          ['Fund. of software Engineering', 'CSE3205'],
          ['Computer Architecture & Organization', 'CSE3203'],
        ],
        sem2: [
          ['Operating System', 'CSE3204'],
          ['Data Communication & Computer Networks', 'CSE3221'],
          ['Introduction to Artificial', 'CSE3206'],
          ['SOftware Requirement Engineering', 'CSE3308'],
          ['Web Programming', 'CSE3306'],
          ['Advanced Programming', 'CSE3312'],
        ],
      },
      Fourth: {
        sem1: [
          ['Formal Language and automata Theory'],
          ['Engineering Research and Development Methodology', 'CSE4221'],
          ['Multimedia Tech.', 'CSE4303'],
          ['Software Design and Architecture', 'CSE4309'],
          ['Mobile Computing and Applications', 'CSE4311'],
          ['Signals and Systems', 'ECE2204'],
          ['Introduction to Data mining', 'CSE5317'],
          ['Introduction to NLP', 'CSE5321'],
          ['Computer System and security', 'Unkown'],
        ],
        sem2: [
          ['Programming languages', 'CSE4202'],
          ['Project Management', 'CSE4302'],
          ['Introduction to Law', 'Unknown'],
          ['Compiler Design', 'CSE4310'],
          ['Digital Signal Processing', 'ECE3205'],
          ['VLSI Design', 'ECE5307'],
          ['Electrical Network Analysis and synthesis', 'PCE3201'],
          ['Introduction to Computer Vision', 'CSE4312'],
        ],
      },
      Fifth: {
        sem1: [
          ['Semester Project', 'CSE5201'],
          ['Seminar', 'CSE5205'],
          ['Distributed Systems', 'CSE5307'],
          ['Wireless mobile Networks', 'CSE5309'],
          ['Image Processing', 'CSE5311'],
          ['Human Computer Interaction', 'CSE5313'],
          ['Introduction to Audio & Video Production', 'CSE5315'],
          ['Advanced Network', 'CSE5319'],
          ['Introduction to Control Systems', 'PCE3204'],
        ],
        sem2: [
          ['B.Sc. Project', 'CSE5202'],
          ['Entrepreneurship for Engineers', 'SOSC412'],
          ['Computer Games & Animation', 'CSE5304'],
          ['Special Topics in Computer Science & Engineering', 'CSE5306'],
          ['Real time and Embedded Systems', 'CSE5308'],
          ['Software Quality & Testing', 'CSE5310'],
          ['Computer Ethics and Social Issues', 'CSE5312'],
          ['Introduction to Robotics and Industrial Automation', 'PCE5308'],
        ],
      },
    },
    SE: {
      Second: {
        sem2: [
          ['Object Oriented Programming', 'CSE2202'],
          ['Discrete Mathematics for CSE', 'CSE2206'],
          ['Digital Logic Design', 'ECE3204'],
          ['Database Systems', 'CSE3207'],
          ['Electronic circuit II', 'ECE2202'],
          ['System Programming', 'CSE2320'],
          ['Computer Graphics', 'CSE3310'],
        ],
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
      },
      Third: {
        sem1: [
          ['Algorithms', 'CSE3211'],
          ['Probability and Random Process', 'ECE3103'],
          ['Fund. of software Engineering', 'CSE3205'],
          ['Computer Architecture & Organization', 'CSE3203'],
        ],
        sem2: [
          ['Operating System', 'CSE3204'],
          ['Data Communication & Computer Networks', 'CSE3221'],
          ['Introduction to Artificial', 'CSE3206'],
          ['SOftware Requirement Engineering', 'CSE3308'],
          ['Web Programming', 'CSE3306'],
          ['Advanced Programming', 'CSE3312'],
        ],
      },
      Fourth: {
        sem1: [
          ['Formal Language and automata Theory'],
          ['Engineering Research and Development Methodology', 'CSE4221'],
          ['Multimedia Tech.', 'CSE4303'],
          ['Software Design and Architecture', 'CSE4309'],
          ['Mobile Computing and Applications', 'CSE4311'],
          ['Signals and Systems', 'ECE2204'],
          ['Introduction to Data mining', 'CSE5317'],
          ['Introduction to NLP', 'CSE5321'],
          ['Computer System and security', 'Unkown'],
        ],
        sem2: [
          ['Programming languages', 'CSE4202'],
          ['Project Management', 'CSE4302'],
          ['Introduction to Law', 'Unknown'],
          ['Compiler Design', 'CSE4310'],
          ['Digital Signal Processing', 'ECE3205'],
          ['VLSI Design', 'ECE5307'],
          ['Electrical Network Analysis and synthesis', 'PCE3201'],
          ['Introduction to Computer Vision', 'CSE4312'],
        ],
      },
      Fifth: {
        sem1: [
          ['Semester Project', 'CSE5201'],
          ['Seminar', 'CSE5205'],
          ['Distributed Systems', 'CSE5307'],
          ['Wireless mobile Networks', 'CSE5309'],
          ['Image Processing', 'CSE5311'],
          ['Human Computer Interaction', 'CSE5313'],
          ['Introduction to Audio & Video Production', 'CSE5315'],
          ['Advanced Network', 'CSE5319'],
          ['Introduction to Control Systems', 'PCE3204'],
        ],
        sem2: [
          ['B.Sc. Project', 'CSE5202'],
          ['Entrepreneurship for Engineers', 'SOSC412'],
          ['Computer Games & Animation', 'CSE5304'],
          ['Special Topics in Computer Science & Engineering', 'CSE5306'],
          ['Real time and Embedded Systems', 'CSE5308'],
          ['Software Quality & Testing', 'CSE5310'],
          ['Computer Ethics and Social Issues', 'CSE5312'],
          ['Introduction to Robotics and Industrial Automation', 'PCE5308'],
        ],
      },
    },
    ECE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [],
      },
      Third: {
        sem1: [[], []],
        sem2: [[], []],
      },
      Fourth: {
        sem1: [[], []],
        sem2: [[], []],
      },
      Fifth: {
        sem1: [[], []],
        sem2: [[], []],
      },
    },
    EPCE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
      Fifth: {
        sem1: [],
        sem2: [],
      },
    },
  },
  SoANS: {
    First: {
      sem1: [
        ['Applied Mathematics I', 'Math1101'],
        ['General Physics I', 'Phys1101'],
        ['Introduction to Computing', 'CSE1101'],
        ['General Biology', 'Bio1101'],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
        ['Health & Physical Education I', 'HPEd1011'],
      ],
      sem2: [
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
        ['Communicative English Skills', 'ENG1011'],
        ['General Chemistry', 'Chem1101'],
        [
          'Applied Mathematics II',
          'Math1102',
          'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
        ],
        ['Statistic and Probability', 'Math1104'],
        [
          'Introduction to Emerging Technologies',
          'CSEg1102',
          'BQACAgQAAxkBAAIHF2HpWjC7fGFjs-9tw0DnwJ45FEK9AAKaCwACCoZIUFfuoRrXPXH3IwQ',
        ],
        ['Health & Physical Education II', 'HPEd1012'],
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
      ],
    },
    AB: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
    AC: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
    P: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
    IC: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
    AG: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
    AM: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
    AP: {
      Second: {
        sem1: [],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
    },
  },
  SoCEA: {
    First: {
      sem1: [
        ['Applied Mathematics I', 'Math1101'],
        ['General Physics-I', 'Phys1101'],
        ['General Chemistry', 'Chem1101'],
        ['Introduction to Computing', 'CSE1101'],
        ['Communicative English Skills', 'ENG1011'],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
        ['Health & Physical Education I', 'HPEd1011'],
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
      ],
      sem2: [
        [
          'Applied Mathematics II',
          'Math1102',
          'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
        ],
        [
          'Introduction to Emerging Technologies',
          'CSEg1102',
          'BQACAgQAAxkBAAIHF2HpWjC7fGFjs-9tw0DnwJ45FEK9AAKaCwACCoZIUFfuoRrXPXH3IwQ',
        ],
        ['Fundamentals of Programming', 'CSEg1104'],
        ['Engineering Drawing', 'DME1102'],
        ['Basic Writing Skills', 'ENG1102'],
        ['Health & Physical Education II', 'HPEd1012'],
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
      ],
    },
    CSE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [
          ['Object Oriented Programming', 'CSE2202'],
          ['Discrete Mathematics for CSE', 'CSE2206'],
          [
            'Digital Logic Design',
            'ECE3204',
            'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
          ],
          ['Database Systems', 'CSE3207'],
          ['Electronic circuit II', 'ECE2202'],
          ['System Programming', 'CSE2320'],
          ['Computer Graphics', 'CSE3310'],
        ],
      },
      Third: {
        sem1: [
          ['Algorithms', 'CSE3211'],
          ['Probability and Random Process', 'ECE3103'],
          ['Fund. of software Engineering', 'CSE3205'],
          ['Computer Architecture & Organization', 'CSE3203'],
        ],
        sem2: [
          ['Operating System', 'CSE3204'],
          ['Data Communication & Computer Networks', 'CSE3221'],
          ['Introduction to Artificial', 'CSE3206'],
          ['SOftware Requirement Engineering', 'CSE3308'],
          ['Web Programming', 'CSE3306'],
          ['Advanced Programming', 'CSE3312'],
        ],
      },
      Fourth: {
        sem1: [
          ['Formal Language and automata Theory'],
          ['Engineering Research and Development Methodology', 'CSE4221'],
          ['Multimedia Tech.', 'CSE4303'],
          ['Software Design and Architecture', 'CSE4309'],
          ['Mobile Computing and Applications', 'CSE4311'],
          ['Signals and Systems', 'ECE2204'],
          ['Introduction to Data mining', 'CSE5317'],
          ['Introduction to NLP', 'CSE5321'],
          ['Computer System and security', 'Unkown'],
        ],
        sem2: [
          ['Programming languages', 'CSE4202'],
          ['Project Management', 'CSE4302'],
          ['Introduction to Law', 'Unknown'],
          ['Compiler Design', 'CSE4310'],
          ['Digital Signal Processing', 'ECE3205'],
          ['VLSI Design', 'ECE5307'],
          ['Electrical Network Analysis and synthesis', 'PCE3201'],
          ['Introduction to Computer Vision', 'CSE4312'],
        ],
      },
      Fifth: {
        sem1: [
          ['Semester Project', 'CSE5201'],
          ['Seminar', 'CSE5205'],
          ['Distributed Systems', 'CSE5307'],
          ['Wireless mobile Networks', 'CSE5309'],
          ['Image Processing', 'CSE5311'],
          ['Human Computer Interaction', 'CSE5313'],
          ['Introduction to Audio & Video Production', 'CSE5315'],
          ['Advanced Network', 'CSE5319'],
          ['Introduction to Control Systems', 'PCE3204'],
        ],
        sem2: [
          ['B.Sc. Project', 'CSE5202'],
          ['Entrepreneurship for Engineers', 'SOSC412'],
          ['Computer Games & Animation', 'CSE5304'],
          ['Special Topics in Computer Science & Engineering', 'CSE5306'],
          ['Real time and Embedded Systems', 'CSE5308'],
          ['Software Quality & Testing', 'CSE5310'],
          ['Computer Ethics and Social Issues', 'CSE5312'],
          ['Introduction to Robotics and Industrial Automation', 'PCE5308'],
        ],
      },
    },
    SE: {
      Second: {
        sem2: [
          ['Object Oriented Programming', 'CSE2202'],
          ['Discrete Mathematics for CSE', 'CSE2206'],
          [
            'Digital Logic Design',
            'ECE3204',
            'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
          ],
          ['Database Systems', 'CSE3207'],
          ['Electronic circuit II', 'ECE2202'],
          ['System Programming', 'CSE2320'],
          ['Computer Graphics', 'CSE3310'],
        ],
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
      },
      Third: {
        sem1: [
          ['Algorithms', 'CSE3211'],
          ['Probability and Random Process', 'ECE3103'],
          ['Fund. of software Engineering', 'CSE3205'],
          ['Computer Architecture & Organization', 'CSE3203'],
        ],
        sem2: [
          ['Operating System', 'CSE3204'],
          ['Data Communication & Computer Networks', 'CSE3221'],
          ['Introduction to Artificial', 'CSE3206'],
          ['SOftware Requirement Engineering', 'CSE3308'],
          ['Web Programming', 'CSE3306'],
          ['Advanced Programming', 'CSE3312'],
        ],
      },
      Fourth: {
        sem1: [
          ['Formal Language and automata Theory'],
          ['Engineering Research and Development Methodology', 'CSE4221'],
          ['Multimedia Tech.', 'CSE4303'],
          ['Software Design and Architecture', 'CSE4309'],
          ['Mobile Computing and Applications', 'CSE4311'],
          ['Signals and Systems', 'ECE2204'],
          ['Introduction to Data mining', 'CSE5317'],
          ['Introduction to NLP', 'CSE5321'],
          ['Computer System and security', 'Unkown'],
        ],
        sem2: [
          ['Programming languages', 'CSE4202'],
          ['Project Management', 'CSE4302'],
          ['Introduction to Law', 'Unknown'],
          ['Compiler Design', 'CSE4310'],
          ['Digital Signal Processing', 'ECE3205'],
          ['VLSI Design', 'ECE5307'],
          ['Electrical Network Analysis and synthesis', 'PCE3201'],
          ['Introduction to Computer Vision', 'CSE4312'],
        ],
      },
      Fifth: {
        sem1: [
          ['Semester Project', 'CSE5201'],
          ['Seminar', 'CSE5205'],
          ['Distributed Systems', 'CSE5307'],
          ['Wireless mobile Networks', 'CSE5309'],
          ['Image Processing', 'CSE5311'],
          ['Human Computer Interaction', 'CSE5313'],
          ['Introduction to Audio & Video Production', 'CSE5315'],
          ['Advanced Network', 'CSE5319'],
          ['Introduction to Control Systems', 'PCE3204'],
        ],
        sem2: [
          ['B.Sc. Project', 'CSE5202'],
          ['Entrepreneurship for Engineers', 'SOSC412'],
          ['Computer Games & Animation', 'CSE5304'],
          ['Special Topics in Computer Science & Engineering', 'CSE5306'],
          ['Real time and Embedded Systems', 'CSE5308'],
          ['Software Quality & Testing', 'CSE5310'],
          ['Computer Ethics and Social Issues', 'CSE5312'],
          ['Introduction to Robotics and Industrial Automation', 'PCE5308'],
        ],
      },
    },
    ECE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [],
      },
      Third: {
        sem1: [[], []],
        sem2: [[], []],
      },
      Fourth: {
        sem1: [[], []],
        sem2: [[], []],
      },
      Fifth: {
        sem1: [[], []],
        sem2: [[], []],
      },
    },
    EPCE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
      Fifth: {
        sem1: [],
        sem2: [],
      },
    },
  },
  SoMCME: {
    First: {
      sem1: [
        ['Applied Mathematics I', 'Math1101'],
        ['General Physics-I', 'Phys1101'],
        ['General Chemistry', 'Chem1101'],
        ['Introduction to Computing', 'CSE1101'],
        ['Communicative English Skills', 'ENG1011'],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
        ['Health & Physical Education I', 'HPEd1011'],
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
      ],
      sem2: [
        [
          'Applied Mathematics II',
          'Math1102',
          'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
        ],
        [
          'Introduction to Emerging Technologies',
          'CSEg1102',
          'BQACAgQAAxkBAAIHF2HpWjC7fGFjs-9tw0DnwJ45FEK9AAKaCwACCoZIUFfuoRrXPXH3IwQ',
        ],
        ['Fundamentals of Programming', 'CSEg1104'],
        ['Engineering Drawing', 'DME1102'],
        ['Basic Writing Skills', 'ENG1102'],
        ['Health & Physical Education II', 'HPEd1012'],
        [
          'Logic and Critical Thinking',
          'LAR1012',
          'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
        ],
        [
          'Civic and Ethical Education',
          'LAR1011',
          'BQACAgQAAxkBAAIHFmHpWjCzwGgrXJ4y0dtofv60bWf5AAKZCwACCoZIUC32zavWn8KSIwQ',
        ],
      ],
    },
    CSE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [
          ['Object Oriented Programming', 'CSE2202'],
          ['Discrete Mathematics for CSE', 'CSE2206'],
          [
            'Digital Logic Design',
            'ECE3204',
            'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
          ],
          ['Database Systems', 'CSE3207'],
          ['Electronic circuit II', 'ECE2202'],
          ['System Programming', 'CSE2320'],
          ['Computer Graphics', 'CSE3310'],
        ],
      },
      Third: {
        sem1: [
          ['Algorithms', 'CSE3211'],
          ['Probability and Random Process', 'ECE3103'],
          ['Fund. of software Engineering', 'CSE3205'],
          ['Computer Architecture & Organization', 'CSE3203'],
        ],
        sem2: [
          ['Operating System', 'CSE3204'],
          ['Data Communication & Computer Networks', 'CSE3221'],
          ['Introduction to Artificial', 'CSE3206'],
          ['SOftware Requirement Engineering', 'CSE3308'],
          ['Web Programming', 'CSE3306'],
          ['Advanced Programming', 'CSE3312'],
        ],
      },
      Fourth: {
        sem1: [
          ['Formal Language and automata Theory'],
          ['Engineering Research and Development Methodology', 'CSE4221'],
          ['Multimedia Tech.', 'CSE4303'],
          ['Software Design and Architecture', 'CSE4309'],
          ['Mobile Computing and Applications', 'CSE4311'],
          ['Signals and Systems', 'ECE2204'],
          ['Introduction to Data mining', 'CSE5317'],
          ['Introduction to NLP', 'CSE5321'],
          ['Computer System and security', 'Unkown'],
        ],
        sem2: [
          ['Programming languages', 'CSE4202'],
          ['Project Management', 'CSE4302'],
          ['Introduction to Law', 'Unknown'],
          ['Compiler Design', 'CSE4310'],
          ['Digital Signal Processing', 'ECE3205'],
          ['VLSI Design', 'ECE5307'],
          ['Electrical Network Analysis and synthesis', 'PCE3201'],
          ['Introduction to Computer Vision', 'CSE4312'],
        ],
      },
      Fifth: {
        sem1: [
          ['Semester Project', 'CSE5201'],
          ['Seminar', 'CSE5205'],
          ['Distributed Systems', 'CSE5307'],
          ['Wireless mobile Networks', 'CSE5309'],
          ['Image Processing', 'CSE5311'],
          ['Human Computer Interaction', 'CSE5313'],
          ['Introduction to Audio & Video Production', 'CSE5315'],
          ['Advanced Network', 'CSE5319'],
          ['Introduction to Control Systems', 'PCE3204'],
        ],
        sem2: [
          ['B.Sc. Project', 'CSE5202'],
          ['Entrepreneurship for Engineers', 'SOSC412'],
          ['Computer Games & Animation', 'CSE5304'],
          ['Special Topics in Computer Science & Engineering', 'CSE5306'],
          ['Real time and Embedded Systems', 'CSE5308'],
          ['Software Quality & Testing', 'CSE5310'],
          ['Computer Ethics and Social Issues', 'CSE5312'],
          ['Introduction to Robotics and Industrial Automation', 'PCE5308'],
        ],
      },
    },
    SE: {
      Second: {
        sem2: [
          ['Object Oriented Programming', 'CSE2202'],
          ['Discrete Mathematics for CSE', 'CSE2206'],
          [
            'Digital Logic Design',
            'ECE3204',
            'BQACAgQAAxkBAAIHGGHpWjAmfKFm-YgOLOluZNle0tEuAAKeCwACCoZIUDbzYMY0qR7AIwQ',
          ],
          ['Database Systems', 'CSE3207'],
          ['Electronic circuit II', 'ECE2202'],
          ['System Programming', 'CSE2320'],
          ['Computer Graphics', 'CSE3310'],
        ],
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
      },
      Third: {
        sem1: [
          ['Algorithms', 'CSE3211'],
          ['Probability and Random Process', 'ECE3103'],
          ['Fund. of software Engineering', 'CSE3205'],
          ['Computer Architecture & Organization', 'CSE3203'],
        ],
        sem2: [
          ['Operating System', 'CSE3204'],
          ['Data Communication & Computer Networks', 'CSE3221'],
          ['Introduction to Artificial', 'CSE3206'],
          ['SOftware Requirement Engineering', 'CSE3308'],
          ['Web Programming', 'CSE3306'],
          ['Advanced Programming', 'CSE3312'],
        ],
      },
      Fourth: {
        sem1: [
          ['Formal Language and automata Theory'],
          ['Engineering Research and Development Methodology', 'CSE4221'],
          ['Multimedia Tech.', 'CSE4303'],
          ['Software Design and Architecture', 'CSE4309'],
          ['Mobile Computing and Applications', 'CSE4311'],
          ['Signals and Systems', 'ECE2204'],
          ['Introduction to Data mining', 'CSE5317'],
          ['Introduction to NLP', 'CSE5321'],
          ['Computer System and security', 'Unkown'],
        ],
        sem2: [
          ['Programming languages', 'CSE4202'],
          ['Project Management', 'CSE4302'],
          ['Introduction to Law', 'Unknown'],
          ['Compiler Design', 'CSE4310'],
          ['Digital Signal Processing', 'ECE3205'],
          ['VLSI Design', 'ECE5307'],
          ['Electrical Network Analysis and synthesis', 'PCE3201'],
          ['Introduction to Computer Vision', 'CSE4312'],
        ],
      },
      Fifth: {
        sem1: [
          ['Semester Project', 'CSE5201'],
          ['Seminar', 'CSE5205'],
          ['Distributed Systems', 'CSE5307'],
          ['Wireless mobile Networks', 'CSE5309'],
          ['Image Processing', 'CSE5311'],
          ['Human Computer Interaction', 'CSE5313'],
          ['Introduction to Audio & Video Production', 'CSE5315'],
          ['Advanced Network', 'CSE5319'],
          ['Introduction to Control Systems', 'PCE3204'],
        ],
        sem2: [
          ['B.Sc. Project', 'CSE5202'],
          ['Entrepreneurship for Engineers', 'SOSC412'],
          ['Computer Games & Animation', 'CSE5304'],
          ['Special Topics in Computer Science & Engineering', 'CSE5306'],
          ['Real time and Embedded Systems', 'CSE5308'],
          ['Software Quality & Testing', 'CSE5310'],
          ['Computer Ethics and Social Issues', 'CSE5312'],
          ['Introduction to Robotics and Industrial Automation', 'PCE5308'],
        ],
      },
    },
    ECE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [],
      },
      Third: {
        sem1: [[], []],
        sem2: [[], []],
      },
      Fourth: {
        sem1: [[], []],
        sem2: [[], []],
      },
      Fifth: {
        sem1: [[], []],
        sem2: [[], []],
      },
    },
    EPCE: {
      Second: {
        sem1: [
          ['Data Structure and Algorithm', 'CSE2101'],
          ['Electronic Circuit', 'ECE2101'],
          [
            'Applied Mathematics III',
            'MATH2051',
            'BQACAgQAAxkBAAIHFGHpWces2va52UDcrtVHcGl5-7oOAAKYCwACCoZIUHtFUaOOCsB2IwQ',
          ],
          ['Fundamental of Electrical Engineering', 'PCE2101'],
          ['Principle of Economics', 'SOS311'],
        ],
        sem2: [],
      },
      Third: {
        sem1: [],
        sem2: [],
      },
      Fourth: {
        sem1: [],
        sem2: [],
      },
      Fifth: {
        sem1: [],
        sem2: [],
      },
    },
  },
};
